### ISSUE TITLE
error in the admin searchfield

### ISSUE THREAD

**Issue by BenZay** [AliYmn/DjangoBan#1]
Hi ! 
I like your app, simple and perfect.

I just want you know you have an error in the admin.py search_fields : 
user_user should be user__username 

i wanted to pull request but i don't know how to do :)

Bye and thanks to share !

**Comment by AliYmn** [comment]
@BenZay Thank you, I fixed the problem. Install the new version of the package :)

`pip uninstall DjangoBan`
`pip install DjangoBan`
