### ISSUE TITLE
I get an error when running DjangoBan

### ISSUE THREAD

**Issue by tetron432** [AliYmn/DjangoBan#2]
Stack Trace error is;
`  File "/usr/local/lib/python3.7/site-packages/ban/models.py", line 7, in UsersBan
    help_text="Choose Username")
TypeError: __init__() missing 1 required positional argument: 'on_delete'`

I am using a custom model for my project.

**Comment by AliYmn** [comment]
Thank you for feedback, i fixed this problem. You can upgrade package 1.9.0 to 2.0.0 version.
